### ISSUE TITLE
Updated instructions on Error Page Handler for AEM 6.3

### ISSUE THREAD

**Issue by paulnolasco** [Adobe-Consulting-Services/adobe-consulting-services.github.io#101]
Team,
One of my client dev team mentioned that our documentation for [Error Page Handler](https://adobe-consulting-services.github.io/acs-aem-commons/features/error-handler/index.html) is obsolete for AEM 6.3. At it stands, it covers AEM 6.2.

We will try to resolve it from our end but can we have an updated guide the covers AEM 6.3? If we do figure it out at some point, I'll ask the client dev team to suggest the changes. 

Thanks!

**Comment by davidjgonzalez** [comment]
@paulnolasco - I'm not sure this is true. Everything documented there should work for 6.3 unless there is a issue/bug.

 Can you clarify what exactly what in the docs  is obsolete?

**Comment by davidjgonzalez** [comment]
Also to be clear; we don't document based on aem versions - we document based on acs commons versions which in turn correlate to aem versions; 3.x works on aem 6.2/6.3

**Comment by paulnolasco** [comment]
Paul,
Ok sounds good. I haven’t really dig deep on the issue that the client
raised. They were just concerned the documentation was called out that it’s
for 6.2, but after an email today from them it looks like it has nothing to
do with this plugin but rather the custom footer that we are using is
causing issue with the plugin. I’ll get more details by tomorrow.

Thanks.

*sincerely,*
*Paul Vincent D. Nolasco*

On August 31, 2017 at 8:23:45 PM, david g. (notifications@github.com) wrote:

Also to be clear; we don't document based on aem versions - we document
based on acs commons versions which in turn correlate to aem versions; 3.x
works on aem 6.2/6.3

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/issues/101#issuecomment-326462422>,
or mute the thread

**Comment by justinedelson** [comment]
The only mention of AEM version on this page says "6.2 and above".
