### ISSUE TITLE
Multifield not working in TouchUI product scaffolding 6.3

### ISSUE THREAD

**Issue by holdsworthr** [Adobe-Consulting-Services/adobe-consulting-services.github.io#114]
We are currently looking to migrate from AEM 6.1 to 6.3

We are currently using the scaffolding TouchUI dialogs to manage some product data which includes a multifield

After porting to 6.3 all other components using multifields are working fine except for those used by the dialogs in the scaffolding

I also get these errors in the browser console

![image](https://user-images.githubusercontent.com/2748821/35615285-9a027ba2-0669-11e8-91a4-33b8104ec7bd.png)

Any help would be gratefully received.

Thanks, Rick.

**Comment by justinedelson** [comment]
@holdsworthr this project is just for the documentation. actual issues with ACS AEM Commons should be created in the acs-aem-commons project.

That said, if you are are on AEM 6.3, you should use the OOTB multifeld and report issues with it to DayCare. See note on https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/multifield-extension/
