### ISSUE TITLE
Need to document that Report Builder doesn't work on 6.2

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/adobe-consulting-services.github.io#115]
@davidjgonzalez remind me how we do this in general? is there a tag or something?

**Comment by davidjgonzalez** [comment]
I don’t think we’ve standardized on how to note 3.x.x feature doesn’t work on 6.2 — I guess just put something at the top of the page? Maybe I’m a block quote (> Requires ARM 6.3+)
