### ISSUE TITLE
Documentation for robots.txt servlet

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/adobe-consulting-services.github.io#198]
Being added in https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/65f1fa0533105ac62ce94e18cf1e008f414efe3b.
@shsteimer Can you provide a basic documentation PR?

**Comment by shsteimer** [comment]
See #194 looks like it has conflicts now, will try to look at those and fix.

**Comment by kwin** [comment]
Sorry, have not checked open PRs before. I will merge once the conflict is solved.

**Comment by kwin** [comment]
Merged https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/194 now.
