### ISSUE TITLE
Clarify compatibility of 5.x

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/adobe-consulting-services.github.io#207]
According to https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/blob/b00f7ea102e769cbf11d13a719c6e6b897f3ea2b/_announcements/acs-aem-commons/5-0-2.txt#L4 version 5.x changes the AEM prerequisites. This is not yet reflected in https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html though.

**Comment by davidjgonzalez** [comment]
Do we know what versions of AEM support the pathed principals? If not I was going to ask on Monday if there's a list somewhere. I didn't see this mentioned in a scan or release notes

**Comment by kwin** [comment]
I just figured out what I stated here: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2523#issuecomment-773484336. Not sure, which AEM version with which SP shipped that bundle.

**Comment by kwin** [comment]
Just checked and AEM 6.4.0 ships with `org.apache.sling.jcr.repoinit` 1.1.8.

**Comment by kwin** [comment]
AEM 6.3 SP3 ships with org.apache.sling.jcr.repoinit 1.1.6 (which does not yet support path directives). Even CFP 6.3.3.8 does not ship a newer one. I have not tried out to execute those repoinits with AEM 6.3.3 though. They should just ignore the path directive IMHO.

**Comment by davidjgonzalez** [comment]
@kwin @wimsymons - I've updated the Compatability matrix: https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html .. let me know if anything looks off.

I lumped 4.x.x all together to be AEM CS incompatible since that's more accurate.
I dropped 6.3.x support from 5.x.x. 

I think dropping 6.3.x is fine if for nothing else, decreasing our testing/bug reporting surface - since 6.3.x is pretty old.

**Comment by joerghoh** [comment]
aren't we able to update the uber.jar then?

(Sorry, was out for some time and didn't follow the development here closely)

**Comment by kwin** [comment]
Yes, but the previous 5.O branch has already updated dependencies for AEM 6.4. That branch has been renamed to 6.0. The 5.x release was initially not thought to change requirements but that turned out to be impossible. The question is whether we backport the relevant commits from branch 6.0 or rather do a 6.0 release soon (tm)

**Comment by kwin** [comment]
https://adobe-consulting-services.github.io/acs-aem-commons/pages/compatibility.html is fine now.
