### ISSUE TITLE
RedirectManager: problems with non-english locale

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Consulting-Services/adobe-consulting-services.github.io#209]
I am testing right now on a Linux system with `LANG=de_DE.UTF-8`. When running the unittests I get a failure at

```
java.lang.NullPointerException: temporal
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1838)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817)
	at com.adobe.acs.commons.redirects.models.RedirectRuleTest.testCreateFromResource(RedirectRuleTest.java:51)

```

Changing the test to use "11 Januar 2021" as ` untilDate` the test works. So this is test has a problem with the locale. 

But going further, it should be validated that RedirectRule functionality also works independently of the underlying locale (not sure if this is the case). Just looking at the code I don't find anything, which enforces to use a fixed locale.

`ImportRedirectMapServletTest` fails for the same reason.

(Anyway, is it really required to define the untilDate as a string? Isn't it possible to use a date within JCR and map that to something which doesn't need the parsing from a String?)

/CC @YegorKozlov

**Comment by YegorKozlov** [comment]
@joerghoh Is the build failing with the 'de' locale or you just seeing the exception?
We've always had it, even with the 'en' locale. This test is to validate that unparsable dates are not fatal. The code logs the error and continues.

**Comment by joerghoh** [comment]
Sorry, I provided a wrong exception trace. I added the correct one.

**Comment by YegorKozlov** [comment]
can you please fire a bug in https://github.com/Adobe-Consulting-Services/acs-aem-commons ?

**Comment by joerghoh** [comment]
@YegorKozlov thanks for that hint ... I've been off for too long :-)

https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2569
