### ISSUE TITLE
Fix embed instructions

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/adobe-consulting-services.github.io#226]
The documentation at https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html for AEMaaCS is incorrect as it misses both the OSGi configuration and bundle from the container package.

In addition the packages should also be added as package dependencies to consuming packages (similar to what is done for the bundle for consumers).

**Comment by kwin** [comment]
@davidjgonzalez Any reason why you don’t recommend to just embed the container package? IMHO cp2fm can deal with it and nesting container packages is totally fine. Otherwise the process is very error prone as a lot of different artifacts need to be embedded separately…

**Comment by davidjgonzalez** [comment]
Honestly, I thought it did!
It doesn't, but it should! 

Don't know how I missed that when making the updates for "min" today - guess I was I on auto pilot and just trying to get those changes out the door.
